# Workflow to be executed on a PR rasie to main, code needs to be build, scanned before merging and deployed to DEV for testing
name: BuildOnPR

on:
  pull_request:
    branches: 
      - main
# We also want to be able to run this manually from Github
  workflow_dispatch:
  

jobs:
  buildASPDotNetCoreReusableWf:
    uses: akshaykumarthakurnew/CloudhackathonSrc/.github/workflows/build_aspdotnetcore.yml@main
    with:
      dotnetverion: 6.0.x
      webAppPubPath: 'src/ContosoUniversity.WebApplication/ContosoUniversity.WebApplication.csproj'
      webApiPubPath: 'src/ContosoUniversity.API/ContosoUniversity.API.csproj'
    #secrets:
    #  envPAT: ${{ secrets.envPAT }}

  lintReusableWF:
    needs: buildASPDotNetCoreReusableWf
    uses: akshaykumarthakurnew/CloudhackathonSrc/.github/workflows/linter.yml@main
  
  scanCodeQLResuableWF:
    needs: buildASPDotNetCoreReusableWf
    uses: akshaykumarthakurnew/CloudhackathonSrc/.github/workflows/CodeQL.yml@main
    
  deployASPDotnetCoreReusableWF:
    needs: [buildASPDotNetCoreReusableWf,scanCodeQLResuableWF,lintReusableWF]
    uses: akshaykumarthakurnew/CloudhackathonSrc/.github/workflows/deploy_aspdotnetcore.yml@main
    with:
      AZURE_API_NAME: Akshay-api
      AZURE_WEBAPP_NAME: Akshay-app
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_CONTOSO_CONN_STRING: ${{ secrets.AZURE_CONTOSO_CONN_STRING }}
      AZURE_CONTOSO_APP_INSIGHTS: ${{ secrets.AZURE_CONTOSO_APP_INSIGHTS }}
    
