# Workflow to be executed for promoting code to QA after successful dev , test phase on DEV env.
name: PromoteToQA

on:
  workflow_dispatch:
  

jobs:
  buildASPDotNetCoreReusableWf:
    uses: akshaykumarthakurnew/CloudhackathonSrc/.github/workflows/build_aspdotnetcore.yml@main
    with:
      dotnetverion: 6.0.x
      webAppPubPath: 'src/ContosoUniversity.WebApplication/ContosoUniversity.WebApplication.csproj'
      webApiPubPath: 'src/ContosoUniversity.API/ContosoUniversity.API.csproj'


  lintReusableWF:
    needs: buildASPDotNetCoreReusableWf
    permissions:
      contents: read
      packages: read
      statuses: write
    uses: akshaykumarthakurnew/CloudhackathonSrc/.github/workflows/linter.yml@main
  
  scanCodeQLResuableWF:
    needs: buildASPDotNetCoreReusableWf
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: akshaykumarthakurnew/CloudhackathonSrc/.github/workflows/CodeQL.yml@main
    
  deployASPDotnetCoreReusableWF:
    needs: [buildASPDotNetCoreReusableWf,scanCodeQLResuableWF,lintReusableWF]
    uses: akshaykumarthakurnew/CloudhackathonSrc/.github/workflows/deploy_aspdotnetcore.yml@main
    with:
      AZURE_API_NAME: Akshay-api
      AZURE_WEBAPP_NAME: Akshay-app
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_CONTOSO_CONN_STRING: ${{ secrets.AZURE_CONTOSO_CONN_STRING }}
      AZURE_CONTOSO_APP_INSIGHTS: ${{ secrets.AZURE_CONTOSO_APP_INSIGHTS }}
    
